### ISSUE TITLE
Wrong address in UI

### ISSUE THREAD

**Issue by PaulRBerg** [OpenZeppelin/starter-kit-gsn#2]
Before creating the Counter instance and funding the recipient, I see the correct address under "Web3 Provider".

After that, I see a bogus address. `0xC957...` is not my MetaMask account.

<img width="974" alt="Screen Shot 2019-08-28 at 16 08 39" src="https://user-images.githubusercontent.com/8782666/63858643-8b4bbd80-c9ae-11e9-98e2-9b2a73a99105.png">

**Comment by ylv-io** [comment]
Hey @PaulRBerg!
Thanks for trying GSN kit.
That shouldn't be your Metamask address because GSN doesn't use Metamask at all. What you see is in memory address generated by `useEphemeralKey ` function.
https://github.com/OpenZeppelin/starter-kit-gsn/blob/fc961179a009462dd4292c76e207381bd112b878/client/src/App.js#L17
What is your particular use case?

**Comment by PaulRBerg** [comment]
I see, thanks Igor.

It's weird, I'm 100% sure I saw my address there, right after tapping the black "Share Address" popup in MetaMask.

And I don't have a specific use case, I was just trying to be a good open-source citizen.

**Comment by ylv-io** [comment]
You'll see your Metamask address there if you use `useWeb3Injected` instead of `useWeb3Network`. The whole idea behind the tutorial is to convert dApp to GSN dApp.
https://github.com/OpenZeppelin/starter-kit-gsn/blob/fc961179a009462dd4292c76e207381bd112b878/client/src/App.js#L34
Checkout awesome [tutorial](https://forum.openzeppelin.com/t/using-gas-station-network-starter-kit-on-a-local-network/1213) by Andrew.
